cube:
  size: 3

pdf:
  title: "CFOP: all 57 OLLs"
  description: All 57 OLLs used for CFOP method

draw:
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: All edges oriented - All corners oriented
    spec:
      - name: OLL 21
        algs:
          - (R U2 R' U') (R U R' U') (R U' R')
      - name: OLL 22
        algs:
          - R U2 (R2 U' R2 U' R2) U2 R
      - name: OLL 23
        algs:
          - R2 D' (R U2 R') D (R U2 R)
      - name: OLL 24
        algs:
          - (r U R' U') (r' F R F')
      - name: OLL 25
        algs:
          - F' (r U R' U') r' F R
      - name: OLL 26 - antisune
        algs:
          - R U2 R' U' R U' R'
      - name: OLL 27 - sune
        algs:
          - R U R' U R U2 R'
      - name: OLL 28
        algs:
          - (r U R' U') r' R (U R U' R')
      - name: OLL 57
        algs:
          - (R U R' U') M' (U R U' r')
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: T shapes - W shapes - Square shapes - P shapes
    spec:
      - name: OLL 33
        algs:
          - (R U R' U') (R' F R F')
      - name: OLL 45
        algs:
          - F (R U R' U') F'
      - name: OLL 36
        algs:
          - (L' U' L U') (L' U L U) (L F' L' F)
      - name: OLL 38
        algs:
          - (R U R' U) (R U' R' U') (R' F R F')
      - name: OLL 5 - Left Fat antisune
        algs:
          - l' U2 L U L' U l
      - name: OLL 6 - Fat antisune
        algs:
          - r U2 R' U' R U' r'
      - name: OLL 31
        algs:
          - R' U' F (U R U' R') F' R
      - name: OLL 32
        algs:
          - L U F' (U' L' U L) F L'
      - name: OLL 43
        algs:
          - F' (U' L' U L) F
      - name: OLL 44
        algs:
          - F (U R U' R') F'
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: Fish shapes - C shapes
    spec:
      - name: OLL 9
        algs:
          - (R U R' U') R' F (R2 U R' U') F'
      - name: OLL 10
        algs:
          - R U R' U (R' F R F') R U2 R'
      - name: OLL 35
        algs:
          - R U2 (R2' F R F') R U2 R'
      - name: OLL 37
        algs:
          - (F R' F' R) (U R U' R')
      - name: OLL 34
        algs:
          - (R U R2 U') R' F R U R U' F'
      - name: OLL 46
        algs:
          - R' U' (R' F R F') U R
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: Small / big lightning bolts
    spec:
      - name: OLL 7
        algs:
          - r U R' U R U2 r'
      - name: OLL 8
        algs:
          - l' U' L U' L' U2 l
      - name: OLL 11
        algs:
          - (r U R' U) (R' F R F') (R U2 r')
      - name: OLL 12
        algs:
          - M' (R' U' R U' R' U2 R) U' R r'
      - name: OLL 39
        algs:
          - L F' (L' U' L U) F U' L'
      - name: OLL 40
        algs:
          - R' F (R U R' U') F' U R
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: L shapes
    spec:
      - name: OLL 47
        algs:
          - R' U' (R' F R F' R' F R F') U R
      - name: OLL 48
        algs:
          - F (R U R' U') (R U R' U') F'
      - name: OLL 49
        algs:
          - r U' (r2 U r2 U r2) U' r
      - name: OLL 50
        algs:
          - r' U (r2 U' r2' U' r2) U r'
      - name: OLL 53
        algs:
          - (l' U2 L U) (L' U' L U) L' U l
      - name: OLL 54
        algs:
          - (r U2 R' U')(R U R' U') R U' r'
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: Knight move shapes, I Shapes
    spec:
      - name: OLL 13
        algs:
          - F (U R U' R2) F' R (U R U' R')
      - name: OLL 14
        algs:
          - R' F R U R' F' R (F U' F')
      - name: OLL 15
        algs:
          - (l' U' l) (L' U' L U) (l' U l)
      - name: OLL 16
        algs:
          - (r U r') (R U R' U') (r U' r')
      - name: OLL 51
        algs:
          - F (U R U' R') (U R U' R') F'
      - name: OLL 52
        algs:
          - (R U R' U) R U' (B U' B') R'
      - name: OLL 55
        algs:
          - R' F R U R U' R2 F' (R2 U' R' U R U R')
      - name: OLL 56
        algs:
          - r' U' r (U' R' U R) (U' R' U R) r' U r
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: Awkward shapes
    spec:
      - name: OLL 29
        algs:
          - (R U R' U') (R U' R') (F' U' F) (R U R')
      - name: OLL 30
        algs:
          - F (R' F R2 U' R' U') (R U R') F2
      - name: OLL 41
        algs:
          - (R U R' U R U2' R') (F R U R' U' F')
          - (R U R' U R U2' R') (T Shapes - OLL 45)
      - name: OLL 42
        algs:
          - (R' U' R U' R' U2 R) (F R U R' U' F')
          - (R' U' R U' R' U2 R) (T Shapes - OLL 45)
  - view: top
    colors:
      - yellow
    preAlg: z2
    title: No edges oriented
    spec:
      - name: OLL 1
        algs:
          - R U2 (R2' F R F') U2 (R' F R F')
      - name: OLL 2
        algs:
          - r U r' U2 r U2 R' U2 R U' r'
          - U' (F R U R' U') (S R U R' U') f'
      - name: OLL 3
        algs:
          - r' (R2 U R' U r U2 r') U M'
      - name: OLL 4
        algs:
          - M U' (r U2 r' U' R U' R') M'
      - name: OLL 17
        algs:
          - F R' F' R2 r' (U R U' R') U' M'
      - name: OLL 18
        algs:
          - (r U R' U R U2 r') (r' U' R U' R' U2 r)
      - name: OLL 19
        algs:
          - r' R U (R U R' U') M' (R' F R F')
      - name: OLL 20
        algs:
          - (r U R' U') M2 (U R U' R') U' M'
